import { describe, expect, it } from "vitest";
import fixture1 from "../fixtures/material-theme-builder/try-01.colormatch.json";
import fixture2 from "../fixtures/material-theme-builder/try-02.colormatch.json";
import fixture3 from "../fixtures/material-theme-builder/try-03.colormatch.json";
import fixture4 from "../fixtures/material-theme-builder/try-04.colormatch.json";
import fixture5 from "../fixtures/material-theme-builder/try-05.colormatch.json";
import { builder } from "./builder";

// Official Material Theme Builder exports, captured with "Color match - Stay
// true to my color inputs" on, for the same inputs as `try-01..05.json`. The
// export does not record the toggle, so each test passes `colorMatch: true`.

// Strip `description` from fixture (present in native Material Theme Builder exports but not generated by builder())
const stripDescription = ({
  description, // eslint-disable-line @typescript-eslint/no-unused-vars
  ...rest
}: Record<string, unknown>) => rest;

describe("builder › toJson() › colorMatch", () => {
  it("should match material theme builder colorMatch fixture 1", () => {
    const result = builder("#769CDF", { colorMatch: true }).toJson();
    expect(result).toEqual(stripDescription(fixture1));
  });

  it("should match material theme builder colorMatch fixture 2", () => {
    const result = builder("#CAB337", {
      colorMatch: true,
      primary: "#CAB337",
      secondary: "#B03A3A",
      tertiary: "#2138D2",
      error: "#479200",
      neutral: "#957FF1",
      neutralVariant: "#007EDF",
      customColors: [
        { name: "Custom Color 1", hex: "#00D68A", blend: true },
        { name: "Custom Color 2", hex: "#FFE16B", blend: true },
      ],
    }).toJson();
    expect(result).toEqual(stripDescription(fixture2));
  });

  it("should match material theme builder colorMatch fixture 3", () => {
    const result = builder("#B33B15", {
      colorMatch: true,
      primary: "#B33B15",
      tertiary: "#009EBE",
      neutralVariant: "#C2C200",
      customColors: [
        { name: "Custom Color 1", hex: "#A4D386", blend: false },
        { name: "Custom Color 2", hex: "#FD0FB6", blend: false },
      ],
    }).toJson();
    expect(result).toEqual(stripDescription(fixture3));
  });

  it("should match material theme builder colorMatch fixture 4", () => {
    const result = builder("#63A002", {
      colorMatch: true,
      primary: "#63A002",
      error: "#FE00FC",
      neutral: "#75003C",
      customColors: [{ name: "Custom Color 1", hex: "#FFD646", blend: true }],
    }).toJson();
    expect(result).toEqual(stripDescription(fixture4));
  });

  it("should match material theme builder colorMatch fixture 5", () => {
    const result = builder("#F766FF", {
      colorMatch: true,
      primary: "#F766FF",
      tertiary: "#7BF600",
      error: "#311E00",
      neutralVariant: "#002726",
      customColors: [
        { name: "Custom Color 1", hex: "#F69C83", blend: true },
        { name: "Custom Color 2", hex: "#8DCCF8", blend: false },
      ],
    }).toJson();
    expect(result).toEqual(stripDescription(fixture5));
  });

  it("should ignore `scheme`: colorMatch forces the content variant", () => {
    const result = builder("#769CDF", {
      colorMatch: true,
      scheme: "expressive",
    }).toJson();
    expect(result).toEqual(stripDescription(fixture1));
  });
});
