import {
  argbFromHex,
  Blend,
  DynamicScheme,
  Hct,
  hexFromArgb,
  MaterialDynamicColors,
  SchemeContent,
  TonalPalette,
} from "@material/material-color-utilities";
import { kebabCase, mapValues, omit, upperFirst } from "lodash-es";
import { describe, expect, it } from "vitest";
import colorMatchFixture from "../fixtures/material-theme-builder/try-01.colormatch.json";
import fixture from "../fixtures/material-theme-builder/try-01.json";
import colorMatchFixture2 from "../fixtures/material-theme-builder/try-02.colormatch.json";
import fixture2 from "../fixtures/material-theme-builder/try-02.json";
import colorMatchFixture3 from "../fixtures/material-theme-builder/try-03.colormatch.json";
import fixture3 from "../fixtures/material-theme-builder/try-03.json";
import colorMatchFixture4 from "../fixtures/material-theme-builder/try-04.colormatch.json";
import fixture4 from "../fixtures/material-theme-builder/try-04.json";
import colorMatchFixture5 from "../fixtures/material-theme-builder/try-05.colormatch.json";
import fixture5 from "../fixtures/material-theme-builder/try-05.json";
import {
  builder,
  DEFAULT_BLEND,
  DEFAULT_COLOR_MATCH,
  type MtbConfig,
  schemeNames,
  schemeToVariant,
  STANDARD_TONES,
  type TokenName,
  tokenNames,
} from "./builder";

// Compare only what Material Theme Builder is authoritative for:
// - `description` is in MTB's exports but not generated by builder();
// - `palettes` are not reproduced: MTB's exported tonal palettes are not the
//   palettes its schemes are drawn from, while ours are (see
//   docs/adr/0001-reference-palettes-are-the-scheme-palettes.md);
// - `background`/`onBackground` are not reproduced: with a `neutral` override,
//   MTB draws them from a palette its schemes do not otherwise use, while ours
//   are the rendered scheme's, as in toCss() (see
//   docs/adr/0002-json-background-follows-the-rendered-scheme.md).
const jsonSchemeNames = [
  "light",
  "light-medium-contrast",
  "light-high-contrast",
  "dark",
  "dark-medium-contrast",
  "dark-high-contrast",
] as const;
const comparable = (json: object) =>
  omit(json, [
    "description",
    "palettes",
    ...jsonSchemeNames.flatMap((name) => [
      `schemes.${name}.background`,
      `schemes.${name}.onBackground`,
    ]),
  ]);

describe("builder › toJson()", () => {
  it("should match material theme builder fixture 1", () => {
    const result = builder("#769CDF").toJson();
    expect(comparable(result)).toEqual(comparable(fixture));
  });

  it("should match material theme builder fixture 2", () => {
    const result = builder("#CAB337", {
      primary: "#CAB337",
      secondary: "#B03A3A",
      tertiary: "#2138D2",
      error: "#479200",
      neutral: "#957FF1",
      neutralVariant: "#007EDF",
      customColors: [
        { name: "Custom Color 1", hex: "#00D68A", blend: true },
        { name: "Custom Color 2", hex: "#FFE16B", blend: true },
      ],
    }).toJson();
    expect(comparable(result)).toEqual(comparable(fixture2));
  });

  it("should match material theme builder fixture 3", () => {
    const result = builder("#B33B15", {
      primary: "#B33B15",
      tertiary: "#009EBE",
      neutralVariant: "#C2C200",
      customColors: [
        { name: "Custom Color 1", hex: "#A4D386", blend: false },
        { name: "Custom Color 2", hex: "#FD0FB6", blend: false },
      ],
    }).toJson();
    expect(comparable(result)).toEqual(comparable(fixture3));
  });

  it("should match material theme builder fixture 4", () => {
    const result = builder("#63A002", {
      primary: "#63A002",
      error: "#FE00FC",
      neutral: "#75003C",
      customColors: [{ name: "Custom Color 1", hex: "#FFD646", blend: true }],
    }).toJson();
    expect(comparable(result)).toEqual(comparable(fixture4));
  });

  it("should match material theme builder fixture 5", () => {
    const result = builder("#F766FF", {
      primary: "#F766FF",
      tertiary: "#7BF600",
      error: "#311E00",
      neutralVariant: "#002726",
      customColors: [
        { name: "Custom Color 1", hex: "#F69C83", blend: true },
        { name: "Custom Color 2", hex: "#8DCCF8", blend: false },
      ],
    }).toJson();
    expect(comparable(result)).toEqual(comparable(fixture5));
  });
});

// ─── Reference palettes ──────────────────────────────────────────────────
//
// `toJson().palettes` holds the reference palettes: the palettes the system
// roles are drawn from, exactly as `toCss()` emits them (#175).

type Input = {
  label: string;
  source: string;
  options?: Omit<MtbConfig, "source">;
};

const inputs: Input[] = [
  // The MTB fixture inputs
  { label: "fixture 1", source: "#769CDF" },
  {
    label: "fixture 2",
    source: "#CAB337",
    options: {
      primary: "#CAB337",
      secondary: "#B03A3A",
      tertiary: "#2138D2",
      error: "#479200",
      neutral: "#957FF1",
      neutralVariant: "#007EDF",
      customColors: [
        { name: "Custom Color 1", hex: "#00D68A", blend: true },
        { name: "Custom Color 2", hex: "#FFE16B", blend: true },
      ],
    },
  },
  {
    label: "fixture 3",
    source: "#B33B15",
    options: {
      primary: "#B33B15",
      tertiary: "#009EBE",
      neutralVariant: "#C2C200",
      customColors: [
        { name: "Custom Color 1", hex: "#A4D386", blend: false },
        { name: "Custom Color 2", hex: "#FD0FB6", blend: false },
      ],
    },
  },
  {
    label: "fixture 4",
    source: "#63A002",
    options: {
      primary: "#63A002",
      error: "#FE00FC",
      neutral: "#75003C",
      customColors: [{ name: "Custom Color 1", hex: "#FFD646", blend: true }],
    },
  },
  {
    label: "fixture 5",
    source: "#F766FF",
    options: {
      primary: "#F766FF",
      tertiary: "#7BF600",
      error: "#311E00",
      neutralVariant: "#002726",
      customColors: [
        { name: "Custom Color 1", hex: "#F69C83", blend: true },
        { name: "Custom Color 2", hex: "#8DCCF8", blend: false },
      ],
    },
  },
  // The #175 repro
  {
    label: "#175 repro",
    source: "#5de4c7",
    options: { scheme: "tonalSpot", contrast: 0 },
  },
  // Contrast and fidelity move roles off their nominal tones
  {
    label: "fidelity, high contrast",
    source: "#5de4c7",
    options: { scheme: "fidelity", contrast: 1 },
  },
  {
    label: "content, medium contrast, custom color",
    source: "#B33B15",
    options: {
      scheme: "content",
      contrast: 0.5,
      customColors: [{ name: "brand", hex: "#00D68A", blend: true }],
    },
  },
];

// The MTB fixture inputs again, with Color match on
const colorMatchInputs: Input[] = inputs
  .filter(({ label }) => label.startsWith("fixture "))
  .map(({ label, source, options }) => ({
    label: `${label}, colorMatch`,
    source,
    options: { ...options, colorMatch: true },
  }));

const allInputs = [...inputs, ...colorMatchInputs];

function hex(argb: number) {
  return hexFromArgb(argb).toUpperCase();
}

// The `--md-ref-palette-<name>-<tone>` values of toCss()'s `:root` rule, in
// the shape of toJson().palettes.
function refPalettesFromCss(css: string) {
  const root = css.slice(css.indexOf(":root {"), css.indexOf(".dark {"));
  const palettes: Record<string, Record<string, string>> = {};

  const refPaletteVar = /--md-ref-palette-([a-z0-9-]+)-(\d+):(#[0-9a-f]{6});/g;
  for (const [, name, tone, value] of root.matchAll(refPaletteVar)) {
    if (!name || !tone || !value) continue;
    palettes[name] ??= {};
    palettes[name][tone] = value.toUpperCase();
  }

  return palettes;
}

// The DynamicScheme builder() renders, rebuilt from the palettes it exposes.
function renderedScheme(
  { source, options = {} }: Input,
  allPalettes: Record<string, TonalPalette>,
  isDark: boolean,
) {
  const palette = (name: string) => {
    const found = allPalettes[name];
    if (!found) throw new Error(`No '${name}' palette`);
    return found;
  };

  const scheme = new DynamicScheme({
    sourceColorArgb: argbFromHex(options.primary ?? source),
    // colorMatch is the Content variant, whatever the `scheme`
    variant:
      schemeToVariant[
        options.colorMatch ? "content" : (options.scheme ?? "tonalSpot")
      ],
    contrastLevel: options.contrast ?? 0,
    isDark,
    primaryPalette: palette("primary"),
    secondaryPalette: palette("secondary"),
    tertiaryPalette: palette("tertiary"),
    neutralPalette: palette("neutral"),
    neutralVariantPalette: palette("neutral-variant"),
  });
  scheme.errorPalette = palette("error");

  return scheme;
}

// The role builder() renders `tokenName` from, and the scheme it reads it on.
//
// That is the token's own role on the rendered scheme, but for the roles of an
// accent overridden under colorMatch: those are the primary roles of the
// Content scheme of the accent's own color (see
// docs/adr/0003-color-match-is-the-content-variant-per-core-color.md), rebuilt
// here around the palette exported for that accent.
function renderedRole(
  input: Input,
  allPalettes: Record<string, TonalPalette>,
  tokenName: TokenName,
  isDark: boolean,
) {
  const scheme = renderedScheme(input, allPalettes, isDark);
  const { options = {} } = input;

  const accent = (["secondary", "tertiary", "error"] as const).find((name) =>
    tokenName.toLowerCase().includes(name),
  );
  const accentHex = accent && options.colorMatch ? options[accent] : undefined;
  if (!accent || !accentHex) {
    return { role: MaterialDynamicColors[tokenName], scheme };
  }

  // eg onSecondaryContainer -> onPrimaryContainer
  const primaryTokenName = tokenName
    .replace(accent, "primary")
    .replace(upperFirst(accent), "Primary") as TokenName;

  return {
    role: MaterialDynamicColors[primaryTokenName],
    scheme: new DynamicScheme({
      sourceColorArgb: argbFromHex(accentHex),
      variant: schemeToVariant.content,
      contrastLevel: options.contrast ?? 0,
      isDark,
      primaryPalette:
        accent === "error" ? scheme.errorPalette : scheme[`${accent}Palette`],
      secondaryPalette: scheme.secondaryPalette,
      tertiaryPalette: scheme.tertiaryPalette,
      neutralPalette: scheme.neutralPalette,
      neutralVariantPalette: scheme.neutralVariantPalette,
    }),
  };
}

describe("builder › toJson().palettes", () => {
  for (const input of allInputs) {
    it(`should equal the --md-ref-palette-* of toCss() (${input.label})`, () => {
      const theme = builder(input.source, input.options);
      const { palettes } = theme.toJson();

      expect(palettes).toEqual(refPalettesFromCss(theme.toCss()));
      expect(palettes).toHaveProperty("error");
      for (const tones of Object.values(palettes)) {
        expect(Object.keys(tones).map(Number)).toEqual([...STANDARD_TONES]);
      }
    });
  }

  for (const input of allInputs) {
    it(`should hold the palette every system role is a tone of (${input.label})`, () => {
      const theme = builder(input.source, input.options);
      const { palettes } = theme.toJson();

      for (const isDark of [false, true]) {
        const rendered = isDark
          ? theme.mergedColorsDark
          : theme.mergedColorsLight;

        for (const tokenName of tokenNames) {
          const { role, scheme } = renderedRole(
            input,
            theme.allPalettes,
            tokenName,
            isDark,
          );
          const roleHex = hex(role.getArgb(scheme));

          // The scheme rebuilt here is the one builder() rendered
          expect(roleHex, tokenName).toBe(hex(rendered[tokenName] ?? 0));

          // The role is a tone of its palette -- at whatever tone contrast
          // and fidelity landed it on, not necessarily an exported one
          const palette = role.palette(scheme);
          expect(roleHex, tokenName).toBe(
            hex(palette.tone(role.getTone(scheme))),
          );

          // ...and that palette is the one exported under its key
          const [name] =
            Object.entries(theme.allPalettes).find(
              ([, exported]) => exported === palette,
            ) ?? [];
          expect(name, tokenName).toBeDefined();
          expect(palettes[kebabCase(name)], tokenName).toEqual(
            Object.fromEntries(
              STANDARD_TONES.map((tone) => [
                tone.toString(),
                hex(palette.tone(tone)),
              ]),
            ),
          );
        }
      }
    });
  }

  for (const input of allInputs) {
    it(`should hold the palette every custom-color role is a tone of (${input.label})`, () => {
      const theme = builder(input.source, input.options);
      const { palettes } = theme.toJson();

      const customColorNames = (input.options?.customColors ?? []).map(
        (color) => color.name,
      );
      expect(Object.keys(theme.customColorRoles)).toEqual(customColorNames);

      // Every rendered color that is not a core role is a custom-color role
      const customTokenNames = Object.values(theme.customColorRoles).flatMap(
        (roles) => Object.keys(roles),
      );
      for (const rendered of [
        theme.mergedColorsLight,
        theme.mergedColorsDark,
      ]) {
        expect(
          Object.keys(rendered).filter(
            (tokenName) =>
              !(tokenNames as readonly string[]).includes(tokenName),
          ),
        ).toEqual(customTokenNames);
      }

      for (const isDark of [false, true]) {
        const scheme = renderedScheme(input, theme.allPalettes, isDark);
        const rendered = isDark
          ? theme.mergedColorsDark
          : theme.mergedColorsLight;

        for (const [customColorName, roles] of Object.entries(
          theme.customColorRoles,
        )) {
          for (const [tokenName, role] of Object.entries(roles)) {
            const roleHex = hex(role.getArgb(scheme));

            // The role is the color builder() renders for it
            expect(roleHex, tokenName).toBe(hex(rendered[tokenName] ?? 0));

            // The role is a tone of its palette -- at whatever tone it
            // landed on, not necessarily an exported one
            const palette = role.palette(scheme);
            expect(roleHex, tokenName).toBe(
              hex(palette.tone(role.getTone(scheme))),
            );

            // ...and that palette is the one exported under its custom
            // color's key
            const [name] =
              Object.entries(theme.allPalettes).find(
                ([, exported]) => exported === palette,
              ) ?? [];
            expect(name, tokenName).toBe(customColorName);
            expect(palettes[kebabCase(customColorName)], tokenName).toEqual(
              Object.fromEntries(
                STANDARD_TONES.map((tone) => [
                  tone.toString(),
                  hex(palette.tone(tone)),
                ]),
              ),
            );
          }
        }
      }
    });
  }
});

// ─── background / onBackground ───────────────────────────────────────────
//
// `toJson().schemes` takes `background` and `onBackground` from the rendered
// scheme, like toCss() -- not, as MTB's export does with a `neutral` override,
// from the scheme of `primary` alone (see
// docs/adr/0002-json-background-follows-the-rendered-scheme.md).

const jsonSchemeLevels = [
  { name: "light", isDark: false, contrast: 0 },
  { name: "light-medium-contrast", isDark: false, contrast: 0.5 },
  { name: "light-high-contrast", isDark: false, contrast: 1.0 },
  { name: "dark", isDark: true, contrast: 0 },
  { name: "dark-medium-contrast", isDark: true, contrast: 0.5 },
  { name: "dark-high-contrast", isDark: true, contrast: 1.0 },
] as const satisfies readonly {
  name: (typeof jsonSchemeNames)[number];
  isDark: boolean;
  contrast: number;
}[];

// The value of `--md-sys-color-<name>` in toCss()'s `:root` (light) or
// `.dark` rule, resolved through the `--md-ref-palette-*` it points at.
function sysColorFromCss(css: string, name: string, isDark: boolean) {
  const start = css.indexOf(isDark ? ".dark {" : ":root {");
  const rule = css.slice(start, css.indexOf("}", start));
  const value = rule.match(new RegExp(`--md-sys-color-${name}:([^;]+);`))?.[1];
  if (!value) throw new Error(`No --md-sys-color-${name}`);

  const refPalette = value.match(
    /^var\(--md-ref-palette-([a-z0-9-]+)-(\d+)\)$/,
  );
  if (!refPalette) return value.toUpperCase();
  const [, palette = "", tone = ""] = refPalette;
  return refPalettesFromCss(css)[palette]?.[tone];
}

describe("builder › toJson().schemes background and onBackground", () => {
  const backgroundInputs = allInputs.filter(({ label }) =>
    ["fixture 1", "fixture 2", "fixture 4"].includes(
      label.replace(", colorMatch", ""),
    ),
  );

  it("should cover the MTB fixtures that override neutral, and one that does not, with and without colorMatch", () => {
    expect(
      backgroundInputs.map(({ label, options }) => [label, options?.neutral]),
    ).toEqual([
      ["fixture 1", undefined],
      ["fixture 2", "#957FF1"],
      ["fixture 4", "#75003C"],
      ["fixture 1, colorMatch", undefined],
      ["fixture 2, colorMatch", "#957FF1"],
      ["fixture 4, colorMatch", "#75003C"],
    ]);
  });

  for (const input of backgroundInputs) {
    it(`should equal toCss() and surface/onSurface in every scheme (${input.label})`, () => {
      const { schemes } = builder(input.source, input.options).toJson();

      for (const { name, isDark, contrast } of jsonSchemeLevels) {
        const css = builder(input.source, {
          ...input.options,
          contrast,
        }).toCss();
        const colors = schemes[name] ?? {};

        expect(colors.background, name).toBe(
          sysColorFromCss(css, "background", isDark),
        );
        expect(colors.onBackground, name).toBe(
          sysColorFromCss(css, "on-background", isDark),
        );

        expect(colors.background, name).toBe(colors.surface);
        // MCU's 2021 spec gives onBackground a lower contrast curve than
        // onSurface, so the two only meet at standard contrast -- in MTB's
        // export as well
        if (contrast === 0) {
          expect(colors.onBackground, name).toBe(colors.onSurface);
        }
      }
    });
  }
});

// ─── Color match ─────────────────────────────────────────────────────────
//
// `colorMatch` is MTB's "Color match - Stay true to my color inputs": the
// Content variant, applied per core color (see
// docs/adr/0003-color-match-is-the-content-variant-per-core-color.md). The
// `try-0N.colormatch.json` fixtures are MTB's exports of the `try-0N.json`
// inputs with Color match on.

function inputByLabel(label: string) {
  const input = allInputs.find((candidate) => candidate.label === label);
  if (!input) throw new Error(`No '${label}' input`);
  return input;
}

describe("builder › toJson() with colorMatch", () => {
  it.each([
    ["fixture 1", colorMatchFixture],
    ["fixture 2", colorMatchFixture2],
    ["fixture 3", colorMatchFixture3],
    ["fixture 4", colorMatchFixture4],
    ["fixture 5", colorMatchFixture5],
  ])(
    "should match material theme builder colorMatch %s",
    (label, colorMatchFixture) => {
      const { source, options } = inputByLabel(`${label}, colorMatch`);
      const result = builder(source, options).toJson();
      expect(comparable(result)).toEqual(comparable(colorMatchFixture));
    },
  );

  it("should be off by default", () => {
    expect(DEFAULT_COLOR_MATCH).toBe(false);
  });

  for (const { label, source, options } of inputs) {
    it(`should render colorMatch: false exactly like an omitted one (${label})`, () => {
      const omitted = builder(source, options);
      const off = builder(source, { ...options, colorMatch: false });

      expect(off.toJson()).toEqual(omitted.toJson());
      expect(off.toCss()).toEqual(omitted.toCss());
    });
  }

  // Guards the tests above: were `colorMatch` to change nothing, `false` would
  // render like an omitted one whatever the default.
  for (const { label, source, options } of colorMatchInputs) {
    it(`should render colorMatch: true differently (${label})`, () => {
      const off = builder(source, { ...options, colorMatch: false });
      const on = builder(source, options);

      expect(on.toJson().schemes).not.toEqual(off.toJson().schemes);
      expect(on.toCss()).not.toEqual(off.toCss());
    });
  }

  // MTB has no scheme selector: Color match off is tonal spot, on is content.
  // So `colorMatch` wins over `scheme`, for the custom colors as well.
  it.each(schemeNames)("should take precedence over scheme: %s", (scheme) => {
    const { source, options } = inputByLabel("fixture 2, colorMatch");
    expect(options?.customColors).not.toHaveLength(0);

    const withScheme = builder(source, { ...options, scheme });
    const withoutScheme = builder(source, options);

    expect(withScheme.toJson()).toEqual(withoutScheme.toJson());
    expect(withScheme.toCss()).toEqual(withoutScheme.toCss());
  });

  // Custom colors have no fixture to conform to (MTB's JSON does not export
  // their roles). They follow MTB's own code instead, which reads them from
  // the scheme of the custom color (harmonized, when `blend` is set): its
  // primary, onPrimary, primaryContainer and onPrimaryContainer. That scheme is
  // the Content variant with Color match on (see
  // docs/adr/0003-color-match-is-the-content-variant-per-core-color.md).
  const customColorInputs = inputs.filter(
    ({ options }) => options?.customColors?.length,
  );

  it("should cover custom colors with and without blend, under another scheme and contrast than the default", () => {
    expect(
      customColorInputs.map(({ options }) => [
        options?.scheme,
        options?.contrast,
        ...(options?.customColors ?? []).map((color) => color.blend),
      ]),
    ).toEqual([
      [undefined, undefined, true, true],
      [undefined, undefined, false, false],
      [undefined, undefined, true],
      [undefined, undefined, true, false],
      ["content", 0.5, true],
    ]);
  });

  // The color a custom color is built from, and the four roles builder()
  // renders for it
  function customColorsOf({ source, options = {} }: Input) {
    const sourceArgb = argbFromHex(options.primary ?? source);

    return (options.customColors ?? []).map((color) => ({
      name: color.name,
      colorHct: Hct.fromInt(
        (color.blend ?? DEFAULT_BLEND)
          ? Blend.harmonize(argbFromHex(color.hex), sourceArgb)
          : argbFromHex(color.hex),
      ),
      roleNames: {
        color: color.name,
        onColor: `on${upperFirst(color.name)}`,
        container: `${color.name}Container`,
        onContainer: `on${upperFirst(color.name)}Container`,
      },
    }));
  }

  for (const input of customColorInputs) {
    const { label, source, options } = input;

    it(`should render each custom color with the primary roles of the Content scheme of its own color (${label})`, () => {
      const theme = builder(source, { ...options, colorMatch: true });
      const { palettes } = theme.toJson();

      const customColors = customColorsOf(input);
      expect(customColors).not.toHaveLength(0);

      for (const { name, colorHct, roleNames } of customColors) {
        for (const isDark of [false, true]) {
          const rendered = isDark
            ? theme.mergedColorsDark
            : theme.mergedColorsLight;
          // At the standard contrast, whatever `contrast`: the roles of a
          // custom color do not follow it, with or without colorMatch
          const content = new SchemeContent(colorHct, isDark, 0);

          expect(
            mapValues(roleNames, (roleName) => hex(rendered[roleName] ?? 0)),
            `${name}, ${isDark ? "dark" : "light"}`,
          ).toEqual({
            color: hex(MaterialDynamicColors.primary.getArgb(content)),
            onColor: hex(MaterialDynamicColors.onPrimary.getArgb(content)),
            container: hex(
              MaterialDynamicColors.primaryContainer.getArgb(content),
            ),
            onContainer: hex(
              MaterialDynamicColors.onPrimaryContainer.getArgb(content),
            ),
          });
        }

        // The palette is the primary palette of that scheme: the custom color
        // keeps its own chroma
        const { primaryPalette } = new SchemeContent(colorHct, false, 0);
        expect(palettes[kebabCase(name)], name).toEqual(
          Object.fromEntries(
            STANDARD_TONES.map((tone) => [
              tone.toString(),
              hex(primaryPalette.tone(tone)),
            ]),
          ),
        );
      }
    });

    // Without colorMatch, nothing changes: a custom color has the hue of its
    // own color, the chroma of the scheme's primary palette, and its roles at
    // their standard tones
    it(`should leave the custom colors as they are without colorMatch (${label})`, () => {
      const theme = builder(source, options);
      const { palettes } = theme.toJson();

      for (const { name, colorHct, roleNames } of customColorsOf(input)) {
        const palette = TonalPalette.fromHueAndChroma(
          colorHct.hue,
          theme.allPalettes.primary.chroma,
        );

        expect(palettes[kebabCase(name)], name).toEqual(
          Object.fromEntries(
            STANDARD_TONES.map((tone) => [
              tone.toString(),
              hex(palette.tone(tone)),
            ]),
          ),
        );

        expect(
          mapValues(roleNames, (roleName) => [
            hex(theme.mergedColorsLight[roleName] ?? 0),
            hex(theme.mergedColorsDark[roleName] ?? 0),
          ]),
          name,
        ).toEqual({
          color: [hex(palette.tone(40)), hex(palette.tone(80))],
          onColor: [hex(palette.tone(100)), hex(palette.tone(20))],
          container: [hex(palette.tone(90)), hex(palette.tone(30))],
          onContainer: [hex(palette.tone(30)), hex(palette.tone(90))],
        });
      }
    });
  }

  for (const { label, source, options } of colorMatchInputs) {
    it(`should render every role as toCss() does, in every scheme (${label})`, () => {
      const { schemes } = builder(source, options).toJson();

      for (const { name, isDark, contrast } of jsonSchemeLevels) {
        const css = builder(source, { ...options, contrast }).toCss();

        for (const [tokenName, color] of Object.entries(schemes[name] ?? {})) {
          expect(color, `${name} ${tokenName}`).toBe(
            sysColorFromCss(css, kebabCase(tokenName), isDark),
          );
        }
      }
    });
  }
});

// ─── schemes vs toCss(), with core-color overrides ───────────────────────
//
// `toJson().schemes` and the `--md-sys-color-*` of toCss() are the same roles,
// read from one scheme: with core-color overrides, whatever the `scheme`.

describe("builder › toJson().schemes with core-color overrides", () => {
  const overrideInputs = inputs.filter(({ label }) =>
    ["fixture 2", "fixture 3", "fixture 4", "fixture 5"].includes(label),
  );

  it("should cover every core-color override", () => {
    const overridden = new Set(
      overrideInputs.flatMap(({ options = {} }) =>
        (
          [
            "primary",
            "secondary",
            "tertiary",
            "error",
            "neutral",
            "neutralVariant",
          ] as const
        ).filter((core) => options[core] !== undefined),
      ),
    );
    expect([...overridden].sort()).toEqual([
      "error",
      "neutral",
      "neutralVariant",
      "primary",
      "secondary",
      "tertiary",
    ]);
  });

  for (const input of overrideInputs) {
    for (const scheme of schemeNames) {
      it(`should equal the roles of toCss() in every scheme (${input.label}, ${scheme})`, () => {
        const options = { ...input.options, scheme };
        const { schemes } = builder(input.source, options).toJson();

        for (const { name, isDark, contrast } of jsonSchemeLevels) {
          const css = builder(input.source, { ...options, contrast }).toCss();

          const cssRoles = Object.fromEntries(
            Object.keys(schemes[name] ?? {}).map((role) => [
              role,
              sysColorFromCss(css, kebabCase(role), isDark),
            ]),
          );
          expect(schemes[name], name).toEqual(cssRoles);
        }
      });
    }
  }
});
