// Generates the files the package ships that are derived from an exporter --
// `tailwind.css` from `toTailwind()`, `shadcn.css` from `toShadcnAliases()`,
// `registry-item.json` from `toShadcnRegistryItem()` -- into `src/` and
// `dist/`.
//
// The stylesheets used to be maintained by hand alongside the exporter they
// mirror, which is how `--color-surface-tint` and `--color-surface-variant`
// came to be missing from one and not the other. Generating them removes the
// possibility: there is one mapping per file now, and the file is its output.
//
//   node scripts/generate.mjs
//
// Every copy is build output and all are gitignored: `dist/` is what ships,
// `src/` is what Storybook `@import`s, so that its stylesheet can dogfood the
// same arrangement the README recommends rather than a second-best one of its
// own. That is why `pnpm run storybook` builds first. The registry item has no
// `src/` copy -- nothing in the repo reads it, it is only ever fetched by
// `shadcn add` from the published package.
//
// Runs from `tsup`'s `onSuccess`, so `pnpm run build` keeps them all current.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import prettier from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// The outputs name variables, never colors, so the source is arbitrary -- every
// exporter here returns the same thing whatever it is asked about. Keep it that
// way: an output that varied with the source would mean this file publishing one
// theme, chosen here, to everyone who installs it. That is why the registry item
// below is built without `{ fallback: true }` -- the variant that does bake
// colors in belongs to the CLI, which is given a real source color.
const SOURCE = "#6750A4";

/**
 * The generated files: which exporter fills each, under which header, in which
 * directories.
 *
 * The headers exist to explain to a reader of `dist/*.css` why editing is
 * futile, and to say what the file deliberately leaves out. JSON has no comment
 * syntax, so `registry-item.json` goes without one -- and needs it less, being
 * a file the `shadcn` CLI reads rather than a human.
 */
const FILES = {
  "tailwind.css": {
    parser: "css",
    dirs: ["src", "dist"],
    banner: `/*
 * Generated by \`scripts/generate.mjs\` -- do not edit.
 *
 * Custom colors are not in here: they depend on your config, so they come from
 * the plugin instead.
 *
 *   @plugin "material-theme-builder/tailwind" {
 *     custom-colors: myCustomColor1, myCustomColor2;
 *   }
 */
`,
    from: (builder) => builder(SOURCE).toTailwind(),
  },
  "shadcn.css": {
    parser: "css",
    dirs: ["src", "dist"],
    banner: `/*
 * Generated by \`scripts/generate.mjs\` -- do not edit.
 *
 * Points shadcn's variables at the M3 custom properties \`<Mtb>\` emits, so
 * shadcn components follow the theme above them in the tree. Import it after
 * shadcn's own \`:root\` and \`.dark\` blocks, which it has to override -- or
 * skip the ordering question entirely and install \`registry-item.json\` with
 * \`shadcn add\`, which writes the same mapping into those blocks in place.
 */
`,
    from: (builder) => builder(SOURCE).toShadcnAliases(),
  },
  "registry-item.json": {
    parser: "json",
    dirs: ["dist"],
    from: (builder) =>
      JSON.stringify(builder(SOURCE).toShadcnRegistryItem(), null, 2),
  },
};

/** Every generated file name, e.g. `tailwind.css`. */
export const GENERATED_FILES = /** @type {(keyof FILES)[]} */ (
  Object.keys(FILES)
);

/**
 * The subset with a `src/` copy — the stylesheets Storybook `@import`s, and so
 * the only ones its dev-server plugin has to keep current.
 */
export const STYLESHEETS = GENERATED_FILES.filter((name) =>
  FILES[name].dirs.includes("src"),
);

/**
 * Wrap an exporter's output into the file as shipped.
 *
 * @param {keyof FILES} name which file, e.g. `tailwind.css`
 * @param {string} body the exporter's output
 * @returns {Promise<string>}
 */
export async function formatOutput(name, body) {
  const { banner = "", parser } = FILES[name];
  const options = await prettier.resolveConfig(join(root, "src", name));

  return prettier.format(banner + body, { ...options, parser });
}

/**
 * A file's contents, from whichever `builder` the caller can reach.
 *
 * Taking it as an argument is what lets Storybook regenerate on the fly: it
 * loads `builder` from source through Vite, where this module can only reach
 * the built bundle.
 *
 * @param {keyof FILES} name which file, e.g. `tailwind.css`
 * @param {(source: string) => Record<string, () => never>} builder
 * @returns {Promise<string>}
 */
export const outputFrom = (name, builder) =>
  formatOutput(name, FILES[name].from(builder));

/**
 * Write `content` to `path`, unless that is what it already says.
 *
 * Only writing on a real change is what leaves the working tree alone when a
 * build has nothing to say -- and, in Storybook, what stops an unrelated edit
 * under `src/lib/` from invalidating the stylesheet and every utility with it.
 *
 * @param {string} path
 * @param {string} content
 * @returns {boolean} whether it wrote
 */
export function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);

  return true;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  // Imported lazily, and through a URL rather than a literal specifier, so
  // that only the writing half needs a build to have happened -- a literal
  // would have Vite resolve `dist/` at transform time when the test imports
  // this module.
  const { builder } = await import(
    new URL("../dist/index.js", import.meta.url).href
  );

  for (const name of GENERATED_FILES) {
    const content = await outputFrom(name, builder);

    for (const dir of FILES[name].dirs) {
      const target = join(dir, name);

      if (writeIfChanged(join(root, target), content))
        console.log(`wrote ${target}`);
    }
  }
}
