// Generates the stylesheets the package ships -- `tailwind.css` from
// `toTailwind()`, `shadcn.css` from `toShadcnAliases()` -- into `src/` and
// `dist/`.
//
// Both used to be maintained by hand alongside the exporter they mirror, which
// is how `--color-surface-tint` and `--color-surface-variant` came to be
// missing from one and not the other. Generating them removes the possibility:
// there is one mapping per file now, and the file is its output.
//
//   node scripts/generate-css.mjs
//
// Every copy is build output and all are gitignored: `dist/` is what ships,
// `src/` is what Storybook `@import`s, so that its stylesheet can dogfood the
// same arrangement the README recommends rather than a second-best one of its
// own. That is why `pnpm run storybook` builds first.
//
// Runs from `tsup`'s `onSuccess`, so `pnpm run build` keeps them all current.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import prettier from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// The outputs name variables, never colors, so the source is arbitrary -- both
// exporters return the same string whatever they are asked about.
const SOURCE = "#6750A4";

/**
 * The generated stylesheets: which exporter fills each, under which header.
 *
 * The headers exist to explain to a reader of `dist/*.css` why editing is
 * futile, and to say what the file deliberately leaves out.
 */
const FILES = {
  "tailwind.css": {
    banner: `/*
 * Generated by \`scripts/generate-css.mjs\` -- do not edit.
 *
 * Custom colors are not in here: they depend on your config, so they come from
 * the plugin instead.
 *
 *   @plugin "material-theme-builder/tailwind" {
 *     custom-colors: myCustomColor1, myCustomColor2;
 *   }
 */
`,
    from: (builder) => builder(SOURCE).toTailwind(),
  },
  "shadcn.css": {
    banner: `/*
 * Generated by \`scripts/generate-css.mjs\` -- do not edit.
 *
 * Points shadcn's variables at the M3 custom properties \`<Mtb>\` emits, so
 * shadcn components follow the theme above them in the tree. Import it after
 * shadcn's own \`:root\` and \`.dark\` blocks, which it has to override.
 */
`,
    from: (builder) => builder(SOURCE).toShadcnAliases(),
  },
};

/** The file names, `tailwind.css` and `shadcn.css`. */
export const CSS_FILES = /** @type {(keyof FILES)[]} */ (Object.keys(FILES));

/**
 * Wrap an exporter's output into the file as shipped.
 *
 * @param {keyof FILES} name which stylesheet, e.g. `tailwind.css`
 * @param {string} body the exporter's output
 * @returns {Promise<string>}
 */
export async function formatCss(name, body) {
  const options = await prettier.resolveConfig(join(root, "src", name));

  return prettier.format(FILES[name].banner + body, {
    ...options,
    parser: "css",
  });
}

/**
 * A file's contents, from whichever `builder` the caller can reach.
 *
 * Taking it as an argument is what lets Storybook regenerate on the fly: it
 * loads `builder` from source through Vite, where this module can only reach
 * the built bundle.
 *
 * @param {keyof FILES} name which stylesheet, e.g. `tailwind.css`
 * @param {(source: string) => Record<string, () => string>} builder
 * @returns {Promise<string>}
 */
export const cssFrom = (name, builder) =>
  formatCss(name, FILES[name].from(builder));

/**
 * Write `css` to `path`, unless that is what it already says.
 *
 * Only writing on a real change is what leaves the working tree alone when a
 * build has nothing to say -- and, in Storybook, what stops an unrelated edit
 * under `src/lib/` from invalidating the stylesheet and every utility with it.
 *
 * @param {string} path
 * @param {string} css
 * @returns {boolean} whether it wrote
 */
export function writeIfChanged(path, css) {
  if (existsSync(path) && readFileSync(path, "utf8") === css) return false;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, css);

  return true;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  // Imported lazily, and through a URL rather than a literal specifier, so
  // that only the writing half needs a build to have happened -- a literal
  // would have Vite resolve `dist/` at transform time when the test imports
  // this module.
  const { builder } = await import(
    new URL("../dist/index.js", import.meta.url).href
  );

  for (const name of CSS_FILES) {
    const css = await cssFrom(name, builder);

    for (const dir of ["src", "dist"]) {
      const target = join(dir, name);

      if (writeIfChanged(join(root, target), css))
        console.log(`wrote ${target}`);
    }
  }
}
