// Generates the exporter-derived files the package ships. Each has one
// mapping behind it, so a hand-maintained copy could drift from it -- and did.
//
// Run from `tsup`'s `onSuccess`. Every copy is gitignored build output: `dist/`
// ships, `src/` is what Storybook `@import`s.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import prettier from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Arbitrary, and has to stay able to be: these outputs name variables, never
// colors. Hence no `{ fallback: true }` below -- baking colors in is for the
// CLI, which is given a real source.
const SOURCE = "#6750A4";

/** Which exporter fills each file, under which banner, into which directories. */
const FILES = {
  "shadcn.css": {
    parser: "css",
    dirs: ["src", "dist"],
    banner: `/*
 * Generated by \`scripts/generate.mjs\` -- do not edit.
 *
 * Points shadcn's variables at the M3 custom properties \`<Mtb>\` emits, so
 * shadcn components follow the theme above them in the tree. Import it with
 * your other imports: the selectors are doubled, so it outranks shadcn's own
 * \`:root\` and \`.dark\` wherever it lands. Or install \`registry-item.json\`
 * with \`shadcn add\`, which writes the same mapping into those blocks.
 */
`,
    from: (builder) => builder(SOURCE).toShadcnAliases(),
  },
  "registry-item.json": {
    parser: "json",
    dirs: ["dist"],
    from: (builder) =>
      JSON.stringify(builder(SOURCE).toShadcnRegistryItem(), null, 2),
  },
};

/** Every generated file name, e.g. `shadcn.css`. */
export const GENERATED_FILES = /** @type {(keyof FILES)[]} */ (
  Object.keys(FILES)
);

/** The subset with a `src/` copy -- what Storybook `@import`s. */
export const STYLESHEETS = GENERATED_FILES.filter((name) =>
  FILES[name].dirs.includes("src"),
);

/**
 * Wrap an exporter's output into the file as shipped.
 *
 * @param {keyof FILES} name which file, e.g. `shadcn.css`
 * @param {string} body the exporter's output
 * @returns {Promise<string>}
 */
export async function formatOutput(name, body) {
  const { banner = "", parser } = FILES[name];
  const options = await prettier.resolveConfig(join(root, "src", name));

  return prettier.format(banner + body, { ...options, parser });
}

/**
 * A file's contents, from whichever `builder` the caller can reach -- this
 * module can only reach `dist/`, Storybook loads `src/` through Vite.
 *
 * @param {keyof FILES} name which file, e.g. `shadcn.css`
 * @param {(source: string) => Record<string, () => never>} builder
 * @returns {Promise<string>}
 */
export const outputFrom = (name, builder) =>
  formatOutput(name, FILES[name].from(builder));

/**
 * Write `content` to `path`, unless that is what it already says -- so a build
 * with nothing to say leaves the working tree alone.
 *
 * @param {string} path
 * @param {string} content
 * @returns {boolean} whether it wrote
 */
export function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);

  return true;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  // A URL rather than a literal specifier: a literal would have Vite resolve
  // `dist/` at transform time when the test imports this module.
  const { builder } = await import(
    new URL("../dist/index.js", import.meta.url).href
  );

  for (const name of GENERATED_FILES) {
    const content = await outputFrom(name, builder);

    for (const dir of FILES[name].dirs) {
      const target = join(dir, name);

      if (writeIfChanged(join(root, target), content))
        console.log(`wrote ${target}`);
    }
  }
}
