// Generates the derived files the package ships. Each has one source behind
// it -- an exporter's mapping, or a component's own file -- so a
// hand-maintained copy could drift from it -- and did.
//
// Run from `tsup`'s `onSuccess`. Every copy is gitignored build output: `dist/`
// ships, `src/` is what Storybook `@import`s.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import prettier from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Arbitrary, and has to stay able to be: these outputs name variables, never
// colors. Hence no `{ fallback: true }` below -- baking colors in is for the
// CLI, which is given a real source.
const SOURCE = "#6750A4";

/**
 * The `scheme` registry item: `<Scheme>`, `<Shades>` and their parts, as
 * source for `shadcn add` to copy into a project.
 *
 * Declared once, in the `registry.json` at the repo root -- the file
 * `shadcn add abernier/material-theme-builder/scheme` reads straight off
 * GitHub. What is built here is the same item with the component's source
 * inlined, exactly what `shadcn build` makes of it, for the package to ship:
 * a copy that is pinned to the version it was published with.
 *
 * The component is embedded as it stands in `src/` -- the file Storybook
 * draws with -- so what gets installed is what the stories show. Its imports
 * need no rewriting: `@/lib/utils` is the alias shadcn itself rewrites to the
 * project's own, and the package is imported by name there (see `paths` in
 * `tsconfig.json` for how that resolves here).
 *
 * No `registryDependencies` on the theme item next to it. That one remaps
 * *shadcn's* variables onto the M3 ones; the poster reads the M3 ones
 * directly, and installing it has no business rewriting anyone's `:root`.
 *
 * `material-theme-builder` is left unversioned, which package managers read
 * as "latest" -- hence new enough to export what the component imports. A
 * range computed here would be the version of whichever build ran last,
 * which `local-release` runs *before* `changeset version`.
 */
function schemeRegistryItem() {
  const { items } = JSON.parse(
    readFileSync(join(root, "registry.json"), "utf8"),
  );
  const item = items.find(({ name }) => name === "scheme");

  return {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    ...item,
    files: item.files.map((file) => ({
      ...file,
      content: readFileSync(join(root, file.path), "utf8"),
    })),
  };
}

/** What fills each file, under which banner, into which directories. */
const FILES = {
  "shadcn.css": {
    parser: "css",
    dirs: ["src", "dist"],
    banner: `/*
 * Generated by \`scripts/generate.mjs\` -- do not edit.
 *
 * Points shadcn's variables at the M3 custom properties \`<Mtb>\` emits, so
 * shadcn components follow the theme above them in the tree. Import it with
 * your other imports: the selectors are doubled, so it outranks shadcn's own
 * \`:root\` and \`.dark\` wherever it lands. Or install \`registry-item.json\`
 * with \`shadcn add\`, which writes the same mapping into those blocks.
 */
`,
    from: (builder) => builder(SOURCE).toShadcnAliases(),
  },
  "registry-item.json": {
    parser: "json",
    dirs: ["dist"],
    from: (builder) =>
      JSON.stringify(builder(SOURCE).toShadcnRegistryItem(), null, 2),
  },
  // Under `r/`, where a shadcn registry keeps its items -- and out of the way
  // of `registry-item.json`, whose name already claims to be *the* item.
  "r/scheme.json": {
    parser: "json",
    dirs: ["dist"],
    from: () => JSON.stringify(schemeRegistryItem(), null, 2),
  },
};

/** Every generated file name, e.g. `shadcn.css`. */
export const GENERATED_FILES = /** @type {(keyof FILES)[]} */ (
  Object.keys(FILES)
);

/** The subset with a `src/` copy -- what Storybook `@import`s. */
export const STYLESHEETS = GENERATED_FILES.filter((name) =>
  FILES[name].dirs.includes("src"),
);

/**
 * Wrap an exporter's output into the file as shipped.
 *
 * @param {keyof FILES} name which file, e.g. `shadcn.css`
 * @param {string} body the exporter's output
 * @returns {Promise<string>}
 */
export async function formatOutput(name, body) {
  const { banner = "", parser } = FILES[name];
  const options = await prettier.resolveConfig(join(root, "src", name));

  return prettier.format(banner + body, { ...options, parser });
}

/**
 * A file's contents, from whichever `builder` the caller can reach -- this
 * module can only reach `dist/`, Storybook loads `src/` through Vite.
 *
 * `r/scheme.json` is the one file no exporter fills, and so the one that can
 * be asked for without a `builder`.
 *
 * @param {keyof FILES} name which file, e.g. `shadcn.css`
 * @param {(source: string) => Record<string, () => never>} [builder]
 * @returns {Promise<string>}
 */
export const outputFrom = (name, builder) =>
  formatOutput(name, FILES[name].from(builder));

/**
 * Write `content` to `path`, unless that is what it already says -- so a build
 * with nothing to say leaves the working tree alone.
 *
 * @param {string} path
 * @param {string} content
 * @returns {boolean} whether it wrote
 */
export function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);

  return true;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  // A URL rather than a literal specifier: a literal would have Vite resolve
  // `dist/` at transform time when the test imports this module.
  const { builder } = await import(
    new URL("../dist/index.js", import.meta.url).href
  );

  for (const name of GENERATED_FILES) {
    const content = await outputFrom(name, builder);

    for (const dir of FILES[name].dirs) {
      const target = join(dir, name);

      if (writeIfChanged(join(root, target), content))
        console.log(`wrote ${target}`);
    }
  }
}
